export const RECEIVE_STORIES = 'RECEIVE_STORIES';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const INIT_COMMENTS = 'INIT_COMMENTS';